スマホ表示に修正
ri-ta222/ri-ta pull request #4
Opened 2019-11-10 16:06 UTC by ri-ta222

修正しました！

2019-11-10 16:24 UTC, takeucheese requested changes
ご確認よろしくお願い致します〜！

2019-11-10 16:24 UTC, takeucheese commented on stylesheet.css
> +@media screen and ( max-width:670px )
ここ、これ以降のCSS構文を{}で囲まないと適応されない気がします！
前のPRの例文を元に修正してみてください〜

2019-11-10 16:24 UTC, takeucheese commented on stylesheet.css
> +@media screen and ( max-width:670px )
また、画面サイズによって読み込むスタイルシートを指定することができるので、ファイル分けてしまってもいいかもです！

下記のサイトの最初の方に載ってます！
https://wemo.tech/839

2019-11-11 13:29 UTC, ri-ta222 commented
cssで新しいファイルを作ってimportしてみたのですが、上手くいかずどこが間違っているか教えて頂きたいです。

2019-11-17 08:51 UTC, takeucheese requested changes
遅くなってしまい申し訳ありません！レビューしました！

2019-11-17 08:51 UTC, takeucheese commented on mobile.css
> +@media screen and ( max-width:670px )
htmlタグでメディアクエリの指定しているので、個々の記述はいらなそうです！

2019-11-17 08:51 UTC, takeucheese commented on stylesheet.css
> +@import url('mobile.css') screen and (max-width: 670px);
ここもいらないはずです！

2019-11-17 08:51 UTC, takeucheese commented on index.html
> -    <link rel="stylesheet" href="stylesheet.css">
この行を消してしまうとPC用のCSSが読み込まれなくなる気がします...

2019-11-17 12:54 UTC, ri-ta222 commented
修正しました。
これで言われた所全て直せてますでしょうか？

2019-11-30 03:16 UTC, takeucheese approved these changes
大変遅くなってしまい申し訳ありません🙏良さそうです！
マージしちゃいましょう！
![LGTM](https://lgtmoon.herokuapp.com/images/23530)

2019-11-30 13:49 UTC, merged